# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openra', '0002_auto_20160312_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='info',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='maps',
            name='policy_adaptations',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
