# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openra', '0004_auto_20160315_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='base64_rules',
            field=models.CharField(blank=True, default='', max_length=100000, null=True),
        ),
    ]
