# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openra', '0006_maps_base64_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='last_for_rsync',
            field=models.BooleanField(default=False),
        ),
    ]
