# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openra', '0007_maps_last_for_rsync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replayplayers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replays',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReplayPlayers',
        ),
        migrations.DeleteModel(
            name='Replays',
        ),
    ]
