# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openra', '0010_auto_20160507_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='last_for_rsync',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='rsync_allow',
        ),
    ]
