# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-28 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openra', '0012_auto_20160511_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapUpgradeLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_run', models.DateTimeField(default=datetime.datetime.now)),
                ('from_version', models.CharField(default='', max_length=100)),
                ('to_version', models.CharField(default='', max_length=100)),
                ('upgrade_output', models.CharField(default='', max_length=10000000)),
                ('map_id', models.ForeignKey(on_delete=models.CASCADE, to='openra.Maps')),
            ],
            options={
                'verbose_name_plural': 'MapUpgradeLogs',
            },
        ),
    ]
