# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2023-01-14 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openra', '0013_mapupgradelogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mod', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Engines',
            },
        ),
    ]
